version: "3.8"

services:
  web-server-reverse-proxy:
    image: nginx
    depends_on:
      - web-server
    environment:
      ADDRESS: "web-server"
    ports:
      - "$WEB_SERVER_NGINX_PORT:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/vacunapp.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/vacunapp.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

  web-server:
    build:
      context: services/web-server
      dockerfile: Dockerfile
    environment:
      JWT_SECRET_KEY: "$JWT_SECRET_KEY"
      LOGIN_HOST: "login"
      VACCINATION_CENTER_HOST: "vaccination-center"
      RESERVE_HOST: "reserve-reverse-proxy"
      NODE_ENV: "production"
    depends_on:
      - login
      - vaccination-center
      - reserve-reverse-proxy
    expose:
      - "80"
    scale: 3

  login:
    build:
      context: services/login
      dockerfile: Dockerfile
    environment:
      DB_USER: "$DB_POSTGRES_USERNAME"
      DB_PASSWORD: "$DB_POSTGRES_PASSWORD"
      DB_SCHEMA: "$DB_POSTGRES_SCHEMA"
      DB_DIALECT: "$DB_POSTGRES_DIALECT"
      JWT_SECRET_KEY: "$JWT_SECRET_KEY"
      DB_HOST: "postgres"
      NODE_ENV: "production"
    depends_on:
      - postgres
    expose:
      - "80"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "$DB_POSTGRES_USERNAME"
      POSTGRES_PASSWORD: "$DB_POSTGRES_PASSWORD"
    expose:
      - '5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  vaccination-center:
    build:
      context: services/vaccination-center
      dockerfile: Dockerfile
    environment:
      DB_USER: "$DB_MONGO_USERNAME"
      DB_PASSWORD: "$DB_MONGO_PASSWORD"
      DB_SCHEMA: "$DB_MONGO_SCHEMA"
      DB_HOST: "mongo"
      NODE_ENV: "production"
    depends_on:
      - mongo
      - redis
    expose:
      - 80

  redis:
    image: "redis:alpine"
    expose:
      - 6379

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$DB_MONGO_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$DB_MONGO_PASSWORD"
    expose:
      - '27017'
    volumes:
      - mongo-volume:/data/db
    command: mongod --quiet --logpath /dev/null

  reserve-reverse-proxy:
    image: nginx
    depends_on:
      - reserve-service
    environment:
      ADDRESS: "reserve-service"
    expose:
      - "80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/mysite.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

  reserve-service:
    build:
      context: services/vaccination-center
      dockerfile: Dockerfile
    environment:
      DB_USER: "$DB_MONGO_USERNAME"
      DB_PASSWORD: "$DB_MONGO_PASSWORD"
      DB_SCHEMA: "$DB_MONGO_SCHEMA"
      DB_HOST: "mongo"
      NODE_ENV: production
    depends_on:
      - mongo
      - id-provider-service-mock
      - sms-provider-service-mock
    expose:
      - "80"
    scale: 3

  id-provider-service-mock:
    build:
      context: external-services-mock/id-provider
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      PYTHONUNBUFFERED: 1

  sms-provider-service-mock:
    build:
      context: external-services-mock/sms-provider
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      PYTHONUNBUFFERED: 1

volumes:
  postgres-volume:
  mongo-volume:
