# TODO(santito): mongoDB service and left apps

version: "3.8"
services:
  pg-db:
    container_name: pg-db
    image: postgres
    environment:
      POSTGRES_USER: "$DB_POSTGRES_USERNAME"
      POSTGRES_PASSWORD: "$DB_POSTGRES_PASSWORD"
    ports:
      - '$DB_POSTGRES_PORT:$DB_POSTGRES_PORT'
    volumes:
      - vacunapp-pg-db:/var/lib/postgresql/data

  mg-db:
    container_name: mg-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$DB_MONGO_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$DB_MONGO_PASSWORD"
    ports:
      - '$DB_MONGO_PORT:$DB_MONGO_PORT'
    volumes:
      - vacunapp-mg-db:/data/db

  login-service:
    container_name: login-service
    build:
      context: services/login
      dockerfile: Dockerfile
    environment:
      DB_DIALECT: "$DB_POSTGRES_DIALECT"
      DB_SCHEMA: "$DB_POSTGRES_SCHEMA"
      DB_USER: "$DB_POSTGRES_USERNAME"
      DB_PASSWORD: "$DB_POSTGRES_PASSWORD"
      DB_HOST: "$DB_POSTGRES_HOST"
      PORT: "$LOGIN_PORT"
      NODE_ENV: "$NODE_ENV"
      JWT_SECRET_KEY: "$JWT_SECRET_KEY"
    depends_on:
      - pg-db
    ports:
      - "$LOGIN_PORT:$LOGIN_PORT"

  vaccination-center-service:
    container_name: vaccination-center-service
    build:
      context: services/vaccination-center
      dockerfile: Dockerfile
    environment:
      DB_SCHEMA: "$DB_MONGO_SCHEMA"
      DB_USER: "$DB_MONGO_USERNAME"
      DB_PASSWORD: "$DB_MONGO_PASSWORD"
      DB_HOST: "$DB_MONGO_HOST"
      PORT: "$VACCINATION_CENTER_PORT"
      NODE_ENV: "$NODE_ENV"
      JWT_SECRET_KEY: "$JWT_SECRET_KEY"
    depends_on:
      - mg-db
    ports:
      - "$VACCINATION_CENTER_PORT:$VACCINATION_CENTER_PORT"

volumes:
  vacunapp-pg-db:
  vacunapp-mg-db: