version: "3.8"

services:
  postgres:
    container_name: "$POSTGRES_CONTAINER_NAME"
    image: postgres
    environment:
      POSTGRES_USER: "$DB_POSTGRES_USERNAME"
      POSTGRES_PASSWORD: "$DB_POSTGRES_PASSWORD"
    expose:
      - '$DB_POSTGRES_PORT'
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  mongo:
    container_name: "$MONGO_CONTAINER_NAME"
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$DB_MONGO_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$DB_MONGO_PASSWORD"
    expose:
      - '$DB_MONGO_PORT'
    volumes:
      - mongo-volume:/data/db
    command: mongod --quiet --logpath /dev/null

  login:
    container_name: "$LOGIN_CONTAINER_NAME"
    build:
      context: services/login
      dockerfile: Dockerfile
    environment:
      DB_USER: "$DB_POSTGRES_USERNAME"
      DB_PASSWORD: "$DB_POSTGRES_PASSWORD"
      DB_SCHEMA: "$DB_POSTGRES_SCHEMA"
      DB_DIALECT: "$DB_POSTGRES_DIALECT"
      DB_HOST: "$POSTGRES_CONTAINER_NAME"
      NODE_ENV: "$NODE_ENV"
      JWT_SECRET_KEY: "$JWT_SECRET_KEY"
    depends_on:
      - postgres
    expose:
      - "80"

  vaccination-center:
    build:
      context: services/vaccination-center
      dockerfile: Dockerfile
    environment:
      DB_USER: "$DB_MONGO_USERNAME"
      DB_PASSWORD: "$DB_MONGO_PASSWORD"
      DB_SCHEMA: "$DB_MONGO_SCHEMA"
      DB_HOST: "$MONGO_CONTAINER_NAME"
      NODE_ENV: "$NODE_ENV"
    depends_on:
      - mongo
    expose:
      - "80"
    scale: 3

  vaccination-center-reverse-proxy:
    image: nginx
    depends_on:
      - vaccination-center
    environment:
      PORT: "80"
      ADDRESS: "vaccination-center"
    expose:
      - "80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/mysite.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

  web-server:
    build:
      context: services/web-server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "$NODE_ENV"
      JWT_SECRET_KEY: "$JWT_SECRET_KEY"
      LOGIN_HOST: "$LOGIN_CONTAINER_NAME"
      VACCINATION_CENTER_HOST: "$VACCINATION_CENTER_REVERSE_PROXY_CONTAINER_NAME"
    depends_on:
      - login
      - vaccination-center
    expose:
      - "80"
    scale: 3

  web-server-reverse-proxy:
    image: nginx
    depends_on:
      - web-server
    environment:
      PORT: "$WEB_SERVER_PORT"
      ADDRESS: "web-server"
    ports:
      - "$WEB_SERVER_PORT:$WEB_SERVER_PORT"
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/vacunapp.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/vacunapp.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

volumes:
  postgres-volume:
  mongo-volume:
