version: "3.8"

services:
  postgres:
    container_name: "$POSTGRES_CONTAINER_NAME"
    image: postgres
    environment:
      POSTGRES_USER: "$DB_POSTGRES_USERNAME"
      POSTGRES_PASSWORD: "$DB_POSTGRES_PASSWORD"
    ports:
      - '$DB_POSTGRES_PORT:$DB_POSTGRES_PORT'
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  mongo:
    container_name: "$MONGO_CONTAINER_NAME"
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$DB_MONGO_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$DB_MONGO_PASSWORD"
    ports:
      - '$DB_MONGO_PORT:$DB_MONGO_PORT'
    volumes:
      - mongo-volume:/data/db
    command: mongod --quiet --logpath /dev/null

  login:
    container_name: "$LOGIN_CONTAINER_NAME"
    build:
      context: services/login
      dockerfile: Dockerfile.dev
    environment:
      DB_USER: "$DB_POSTGRES_USERNAME"
      DB_PASSWORD: "$DB_POSTGRES_PASSWORD"
      DB_SCHEMA: "$DB_POSTGRES_SCHEMA"
      DB_DIALECT: "$DB_POSTGRES_DIALECT"
      DB_HOST: "$POSTGRES_CONTAINER_NAME"
      NODE_ENV: "development"
      JWT_SECRET_KEY: "$JWT_SECRET_KEY"
    depends_on:
      - postgres
    ports:
      - "$LOGIN_PORT:80"
    volumes:
      - ./services/login/src:/app/src

  vaccination-center:
    build:
      context: services/vaccination-center
      dockerfile: Dockerfile.dev
    environment:
      DB_USER: "$DB_MONGO_USERNAME"
      DB_PASSWORD: "$DB_MONGO_PASSWORD"
      DB_SCHEMA: "$DB_MONGO_SCHEMA"
      DB_HOST: "$MONGO_CONTAINER_NAME"
      NODE_ENV: "development"
      USER_ID_LENGTH: "$USER_ID_LENGTH"
    depends_on:
      - mongo
    ports:
      - "$VACCINATION_CENTER_PORT:80"
    volumes:
      - ./services/vaccination-center/src:/app/src

  web-server:
    build:
      context: services/web-server
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: "development"
      JWT_SECRET_KEY: "$JWT_SECRET_KEY"
      LOGIN_HOST: "$LOGIN_CONTAINER_NAME"
      VACCINATION_CENTER_HOST: "vaccination-center"
    depends_on:
      - login
      - vaccination-center
    ports:
      - "$WEB_SERVER_PORT:80"
    volumes:
      - ./services/web-server/src:/app/src

volumes:
  postgres-volume:
  mongo-volume:
