### Login

POST localhost:{{web-server-port}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "lorem@ipsum.com",
  "password": "dolor_sit_amet"
}

> {% client.global.set("auth_token", response.headers.valueOf('auth-token')); %}

### Create Vaccination Center

POST localhost:{{web-server-port}}/vaccination-centers HTTP/1.1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "department": 2,
  "departmentZone": 12,
  "id": "antel_arena",
  "name": "Antel Arena",
  "workingTime": 1
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 200");
});
%}

### Create Vaccination Period

POST localhost:{{web-server-port}}/vaccination-centers/vaccination-period
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "departmentId": 1,
  "departmentZone": 4,
  "vaccinationCenterId": "antel_arena",
  "dateFrom": {
    "day": 1,
    "month": 2,
    "year": 2020
  },
  "dateTo": {
    "day": 1,
    "month": 3,
    "year": 2020
  },
  "amountOfVaccines": 2,
  "selectionCriteria": {
    "age": {
      "from": 48,
      "to": 46
    }
  }
}
