POST localhost:{{login-port}}/login
Content-Type: application/json

{
  "email": "lorem@ipsum.com",
  "password": "dolor_sit_amet"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
